logging:
  level:
    org.springframework.web: ERROR
    com.simpleproject: ERROR
spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  h2.console:
    enabled: true
    path: /h2
  mvc.view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp